- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name : stop docker container
    command : sudo docker stop cont

  - name : remove docker container
    command : sudo docker rm cont

  - name: Deploy Docker Container
    command: docker run -itd --name cont -p 8084:8081 jaya002/web-server:latest
